apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lxcv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0099-tenant/ci1t-43256-0099-app/devfile-sample-lxcv@sha256:a2d034b47a0e9653df3236d16f3133f22546c2da42288a0d17ec9c8cc2d8bd54
        name: my-nodejs
        resources: {}
status: {}
